### ISSUE TITLE
Clear up the profile dropdown

### ISSUE THREAD

**Issue by palves-ulht** [a22104341/ANEPC_TFC#3]
The dropdown associated with the current user shows two actions that shouldn't exist:

![CleanShot 2024-05-18 at 15 42 44](https://github.com/a22104341/ANEPC_TFC/assets/10359239/7c34518c-0556-4595-8dd3-9ae9445f1bd6)

Also, logout should be renamed to "Sair"

**Comment by a22104341** [comment]
Meti "Terminar Sessão"
