### ISSUE TITLE
Improve the CTO download page

### ISSUE THREAD

**Issue by palves-ulht** [a22104341/ANEPC_TFC#6]
Right now, this page is a little misterious:

![CleanShot 2024-05-18 at 15 56 46](https://github.com/a22104341/ANEPC_TFC/assets/10359239/d318f0ee-3711-4c8d-8d7d-4fec9af6c39e)

I think the "Page4 :D" isn't needed. However, an explanation would be nice, on top of the button. Something like:

A informação relativa ao CTO XXX/YYYY foi guardada com sucesso. Utilize o botão abaixo para gerar um pdf com essa informação.

**Comment by a22104341** [comment]
Removi a segunda frase, mas a 1a frase agora existe
